### ISSUE TITLE
Change the buggy line

### ISSUE THREAD

**Issue by karanpanjabi** [Sheepposu/discord.py#2]
### Summary

This line should be just self._hook(msg)
https://github.com/Sheepposu/discord.py/blob/3614087f99eff2d99054d5274e1aabe0a06b9852/discord/gateway.py#L836

### Reproduction Steps

The repo gives an error when trying to record without changing this line.

### Expected Results

-

### Actual Results

-

### Intents

-

### System Information

-

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Sheepposu** [comment]
Sorry that this is a month old and I still haven’t done anything about it. Later I’ll test this out (or at least I hope that I remember to)
